<?php
$this->title = "Delete Person";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete this person?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="person_id" value="<?php echo $this->person['person_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>