<?php
$this->title = "Delete User Role";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete this role (<?php echo $this->role['role']; ?>)?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="role_id" value="<?php echo $this->role['role_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>