<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' | ');
$this->headTitle('ICMCMIS');

echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
    
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');?>
    
</head>

<body>

    <div id="content">

        <h1>
        <?php echo $this->escape($this->title); ?>
        </h1>

        <?php echo $this->layout()->content; ?>

    </div>

<div id="footer">
<ul class="footer">
<!--<li><a href="#">Help</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Feedback</a></li>
<li><a href="#">Terms</a></li>
<li><a href="#">Privacy</a></li>
<li><a href="#">Credits</a></li>-->
</ul>
<div class="copyright"><p>&copy; 2012</p><p>e-consultsystems</p></div>
</div>
   
</body>
</html>
