<?php
$this->title = "Delete Encounter";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete this encounter?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="encounter_id" value="<?php echo $this->encounter['encounter_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>