<?php
$this->title = "Encounters";
$this->headTitle($this->title);
?>

<p><a href="<?php echo $this->url(array('controller'=>'encounter',
'action'=>'add'));?>">Add new encounter</a></p>

<table>
    <tr>
        <th>Patient ID</th>
        <th>Encounter Date</th>
        <th>Received By</th>
        <th>Encounter Type</th>
        <th>&nbsp;</th>
    </tr>

<?php foreach($this->encounters as $encounter) : ?>
    
    <tr>
        <td><?php echo $this->escape($encounter['patient_id']);?></td>
        <td><?php echo $this->escape($encounter['date_of_encounter']);?></td>
        <td><?php echo $this->escape($encounter['received_by']);?></td>
        <td><?php echo $this->escape($encounter['encounter_type']);?></td>
        <td>
            
            <a href="<?php echo $this->url(array('controller'=>'encounter',
                'action'=>'edit', 'encounter_id'=>$encounter['encounter_id']));?>">Edit</a>
            
            <a href="<?php echo $this->url(array('controller'=>'encounter',
                'action'=>'delete', 'encounter_id'=>$encounter['encounter_id']));?>">Delete</a>
        </td>
    </tr>
            <?php endforeach; ?>
</table>