<?php
$this->title = "Delete Patient";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete this patient?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="patient_id" value="<?php echo $this->patient['patient_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>