<?php
$this->title = "Delete User";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete this user?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="user_id" value="<?php echo $this->user['user_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>